In [2]:
import pandas as pd
import numpy as np

In [8]:

df = pd.read_csv("C:\\Users\\rohit\\Downloads\\economy.csv.zip")

In [9]:
df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
0,11-02-2022,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953"
1,11-02-2022,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953"
2,11-02-2022,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956"
3,11-02-2022,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955"
4,11-02-2022,Vistara,UK,963,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955"

In [11]:
df['dep_time']

0         18:55
1         06:20
2         04:25
3         10:20
4         08:50
          ...
206769    07:05
206770    07:05
206771    12:30
206772    09:45
206773    20:30
Name: dep_time, Length: 206774, dtype: object

In [13]:
df['dep_time'].isnull().sum()

np.int64(0)

In [17]:
df['hour']=df['dep_time'].str.split(':').str[0]
df['minute']=df['dep_time'].str.split(':').str[1]

In [24]:
df['hour']=df['hour'].astype(int)
df['minute']=df['minute'].astype(int)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 13 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        206774 non-null  object
 1   airline     206774 non-null  object
 2   ch_code     206774 non-null  object
 3   num_code    206774 non-null  int64
 4   dep_time    206774 non-null  object
 5   from        206774 non-null  object
 6   time_taken  206774 non-null  object
 7   stop        206774 non-null  object
 8   arr_time    206774 non-null  object
 9   to          206774 non-null  object
 10  price       206774 non-null  object
 11  hour        206774 non-null  int64
 12  minute      206774 non-null  int64
dtypes: int64(3), object(10)
memory usage: 20.5+ MB

In [26]:
df.drop('dep_time',axis=1,inplace=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        206774 non-null  object
 1   airline     206774 non-null  object
 2   ch_code     206774 non-null  object
 3   num_code    206774 non-null  int64
 4   from        206774 non-null  object
 5   time_taken  206774 non-null  object
 6   stop        206774 non-null  object
 7   arr_time    206774 non-null  object
 8   to          206774 non-null  object
 9   price       206774 non-null  object
 10  hour        206774 non-null  int64
 11  minute      206774 non-null  int64
dtypes: int64(3), object(9)
memory usage: 18.9+ MB

In [28]:
df.head()

,date,airline,ch_code,num_code,from,time_taken,stop,arr_time,to,price,hour,minute
0,11-02-2022,SpiceJet,SG,8709,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953",18,55
1,11-02-2022,SpiceJet,SG,8157,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953",6,20
2,11-02-2022,AirAsia,I5,764,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956",4,25
3,11-02-2022,Vistara,UK,995,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955",10,20
4,11-02-2022,Vistara,UK,963,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955",8,50

In [29]:
df['date']

0         11-02-2022
1         11-02-2022
2         11-02-2022
3         11-02-2022
4         11-02-2022
             ...
206769    31-03-2022
206770    31-03-2022
206771    31-03-2022
206772    31-03-2022
206773    31-03-2022
Name: date, Length: 206774, dtype: object

In [32]:
df['day']=df['date'].str.split('-').str[0].astype(int)
df['month']=df['date'].str.split('-').str[1].astype(int)    
df['year']=df['date'].str.split('-').str[2].astype(int)

In [33]:
df['day']

0         11
1         11
2         11
3         11
4         11
          ..
206769    31
206770    31
206771    31
206772    31
206773    31
Name: day, Length: 206774, dtype: int64

In [34]:
df.head()

,date,airline,ch_code,num_code,from,time_taken,stop,arr_time,to,price,hour,minute,day,month,year
0,11-02-2022,SpiceJet,SG,8709,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953",18,55,11,2,2022
1,11-02-2022,SpiceJet,SG,8157,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953",6,20,11,2,2022
2,11-02-2022,AirAsia,I5,764,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956",4,25,11,2,2022
3,11-02-2022,Vistara,UK,995,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955",10,20,11,2,2022
4,11-02-2022,Vistara,UK,963,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955",8,50,11,2,2022

In [35]:
df.drop('date',axis=1,inplace=True)

In [36]:
df.head()

,airline,ch_code,num_code,from,time_taken,stop,arr_time,to,price,hour,minute,day,month,year
0,SpiceJet,SG,8709,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953",18,55,11,2,2022
1,SpiceJet,SG,8157,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953",6,20,11,2,2022
2,AirAsia,I5,764,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956",4,25,11,2,2022
3,Vistara,UK,995,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955",10,20,11,2,2022
4,Vistara,UK,963,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955",8,50,11,2,2022

In [41]:
df['to'].unique()

array(['Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai', 'Delhi'],
      dtype=object)

In [42]:
df['to'].mode()[0]

'Delhi'

In [43]:
df['time_taken']

0         02h 10m
1         02h 20m
2         02h 10m
3         02h 15m
4         02h 20m
           ...
206769    13h 50m
206770    13h 50m
206771    20h 35m
206772    23h 20m
206773    24h 25m
Name: time_taken, Length: 206774, dtype: object

In [45]:
df['time_taken'][0]

'02h 10m'

In [61]:
df['time_taken_hour']=df['time_taken'].str.split('h').str[0]
df['time_taken_minute']=df['time_taken'].str.split('h').str[1].str.replace('m','')

KeyError: 'time_taken'

In [51]:
df['time_taken_hour']

0         02
1         02
2         02
3         02
4         02
          ..
206769    13
206770    13
206771    20
206772    23
206773    24
Name: time_taken_hour, Length: 206774, dtype: object

In [54]:
df['time_taken_minute']

0          10
1          20
2          10
3          15
4          20
         ...
206769     50
206770     50
206771     35
206772     20
206773     25
Name: time_taken_minute, Length: 206774, dtype: object

In [55]:
df.head()

,airline,ch_code,num_code,from,time_taken,stop,arr_time,to,price,hour,minute,day,month,year,time_taken_hour,time_taken_minute
0,SpiceJet,SG,8709,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953",18,55,11,2,2022,02,10
1,SpiceJet,SG,8157,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953",6,20,11,2,2022,02,20
2,AirAsia,I5,764,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956",4,25,11,2,2022,02,10
3,Vistara,UK,995,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955",10,20,11,2,2022,02,15
4,Vistara,UK,963,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955",8,50,11,2,2022,02,20

In [56]:
df.drop('time_taken',axis=1,inplace=True)

In [57]:
df.head()

,airline,ch_code,num_code,from,stop,arr_time,to,price,hour,minute,day,month,year,time_taken_hour,time_taken_minute
0,SpiceJet,SG,8709,Delhi,non-stop,21:05,Mumbai,"5,953",18,55,11,2,2022,02,10
1,SpiceJet,SG,8157,Delhi,non-stop,08:40,Mumbai,"5,953",6,20,11,2,2022,02,20
2,AirAsia,I5,764,Delhi,non-stop,06:35,Mumbai,"5,956",4,25,11,2,2022,02,10
3,Vistara,UK,995,Delhi,non-stop,12:35,Mumbai,"5,955",10,20,11,2,2022,02,15
4,Vistara,UK,963,Delhi,non-stop,11:10,Mumbai,"5,955",8,50,11,2,2022,02,20

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   airline            206774 non-null  object
 1   ch_code            206774 non-null  object
 2   num_code           206774 non-null  int64
 3   from               206774 non-null  object
 4   stop               206774 non-null  object
 5   arr_time           206774 non-null  object
 6   to                 206774 non-null  object
 7   price              206774 non-null  object
 8   hour               206774 non-null  int64
 9   minute             206774 non-null  int64
 10  day                206774 non-null  int64
 11  month              206774 non-null  int64
 12  year               206774 non-null  int64
 13  time_taken_hour    206774 non-null  object
 14  time_taken_minute  206774 non-null  object
dtypes: int64(6), object(9)
memory usage: 23.7+ MB

In [66]:
df['time_taken_hour']
df['time_taken_minute']

0          10
1          20
2          10
3          15
4          20
         ...
206769     50
206770     50
206771     35
206772     20
206773     25
Name: time_taken_minute, Length: 206774, dtype: object

In [67]:
df.head()

,airline,ch_code,num_code,from,stop,arr_time,to,price,hour,minute,day,month,year,time_taken_hour,time_taken_minute
0,SpiceJet,SG,8709,Delhi,non-stop,21:05,Mumbai,"5,953",18,55,11,2,2022,02,10
1,SpiceJet,SG,8157,Delhi,non-stop,08:40,Mumbai,"5,953",6,20,11,2,2022,02,20
2,AirAsia,I5,764,Delhi,non-stop,06:35,Mumbai,"5,956",4,25,11,2,2022,02,10
3,Vistara,UK,995,Delhi,non-stop,12:35,Mumbai,"5,955",10,20,11,2,2022,02,15
4,Vistara,UK,963,Delhi,non-stop,11:10,Mumbai,"5,955",8,50,11,2,2022,02,20

In [68]:
df['arr_time']

0         21:05
1         08:40
2         06:35
3         12:35
4         11:10
          ...
206769    20:55
206770    20:55
206771    09:05
206772    09:05
206773    20:55
Name: arr_time, Length: 206774, dtype: object

In [70]:
df['arr_time_hour']=df['arr_time'].str.split(':').str[0].astype(int)
df['arr_time_minute']=df['arr_time'].str.split(':').str[1].astype(int)

In [71]:
df.head()

,airline,ch_code,num_code,from,stop,arr_time,to,price,hour,minute,day,month,year,time_taken_hour,time_taken_minute,arr_time_hour,arr_time_minute
0,SpiceJet,SG,8709,Delhi,non-stop,21:05,Mumbai,"5,953",18,55,11,2,2022,02,10,21,5
1,SpiceJet,SG,8157,Delhi,non-stop,08:40,Mumbai,"5,953",6,20,11,2,2022,02,20,8,40
2,AirAsia,I5,764,Delhi,non-stop,06:35,Mumbai,"5,956",4,25,11,2,2022,02,10,6,35
3,Vistara,UK,995,Delhi,non-stop,12:35,Mumbai,"5,955",10,20,11,2,2022,02,15,12,35
4,Vistara,UK,963,Delhi,non-stop,11:10,Mumbai,"5,955",8,50,11,2,2022,02,20,11,10

In [72]:
df.drop('arr_time',axis=1,inplace=True)

In [73]:
df.head()

,airline,ch_code,num_code,from,stop,to,price,hour,minute,day,month,year,time_taken_hour,time_taken_minute,arr_time_hour,arr_time_minute
0,SpiceJet,SG,8709,Delhi,non-stop,Mumbai,"5,953",18,55,11,2,2022,02,10,21,5
1,SpiceJet,SG,8157,Delhi,non-stop,Mumbai,"5,953",6,20,11,2,2022,02,20,8,40
2,AirAsia,I5,764,Delhi,non-stop,Mumbai,"5,956",4,25,11,2,2022,02,10,6,35
3,Vistara,UK,995,Delhi,non-stop,Mumbai,"5,955",10,20,11,2,2022,02,15,12,35
4,Vistara,UK,963,Delhi,non-stop,Mumbai,"5,955",8,50,11,2,2022,02,20,11,10

In [74]:
df['price'].isnull().sum()

np.int64(0)

In [76]:
df['airline'].value_counts().isnull().sum()

np.int64(0)

In [79]:
df['airline'].unique().tolist()

['SpiceJet',
 'AirAsia',
 'Vistara',
 'GO FIRST',
 'Indigo',
 'Air India',
 'Trujet',
 'StarAir']

In [88]:
!pip install scikit-learn
from sklearn.preprocessing import OneHotEncoder as onehotencoder
ohe=onehotencoder()
encoded_airline=ohe.fit_transform(df['airline'].values.reshape(-1,1)).toarray()
encoded_airline_df=pd.DataFrame(encoded_airline,columns=ohe.get_feature_names_out(['airline']))
encoded_airline_df.head()
df=pd.concat([df,encoded_airline_df],axis=1)
df.head()

Requirement already satisfied: scikit-learn in c:\users\rohit\onedrive\desktop\python\venv\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\rohit\onedrive\desktop\python\venv\lib\site-packages (from scikit-learn) (2.3.4)
Requirement already satisfied: scipy>=1.10.0 in c:\users\rohit\onedrive\desktop\python\venv\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\rohit\onedrive\desktop\python\venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\rohit\onedrive\desktop\python\venv\lib\site-packages (from scikit-learn) (3.6.0)

,airline,ch_code,num_code,from,stop,to,price,hour,minute,day,...,arr_time_hour,arr_time_minute,airline_Air India,airline_AirAsia,airline_GO FIRST,airline_Indigo,airline_SpiceJet,airline_StarAir,airline_Trujet,airline_Vistara
0,SpiceJet,SG,8709,Delhi,non-stop,Mumbai,"5,953",18,55,11,...,21,5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,SpiceJet,SG,8157,Delhi,non-stop,Mumbai,"5,953",6,20,11,...,8,40,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,AirAsia,I5,764,Delhi,non-stop,Mumbai,"5,956",4,25,11,...,6,35,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Vistara,UK,995,Delhi,non-stop,Mumbai,"5,955",10,20,11,...,12,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,Vistara,UK,963,Delhi,non-stop,Mumbai,"5,955",8,50,11,...,11,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [89]:
df.drop('airline',axis=1,inplace=True)

In [90]:
df.head()

,ch_code,num_code,from,stop,to,price,hour,minute,day,month,...,arr_time_hour,arr_time_minute,airline_Air India,airline_AirAsia,airline_GO FIRST,airline_Indigo,airline_SpiceJet,airline_StarAir,airline_Trujet,airline_Vistara
0,SG,8709,Delhi,non-stop,Mumbai,"5,953",18,55,11,2,...,21,5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,SG,8157,Delhi,non-stop,Mumbai,"5,953",6,20,11,2,...,8,40,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,I5,764,Delhi,non-stop,Mumbai,"5,956",4,25,11,2,...,6,35,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,UK,995,Delhi,non-stop,Mumbai,"5,955",10,20,11,2,...,12,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,UK,963,Delhi,non-stop,Mumbai,"5,955",8,50,11,2,...,11,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [8]:
import pandas as pd
import numpy as np

NameError: name 'df' is not defined

:

In [81]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\rohit\onedrive\desktop\python\venv\lib\site-packages (from scikit-learn) (2.3.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.0 MB 7.2 MB/s eta 0:00:01
   ----------- ---------------------------- 2.4/8.0 MB 6.7 MB/s eta 0:00:01
   ---------------- ----------------------- 3.4/8.0 MB 6.1 MB/s eta 0:00:01
   ------------------------ --------------- 5.0/8.0 MB 6.4 MB/s eta 0:00:01
   ------------------------------- -------- 6.3/8.0 MB 6.4 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.0 MB 6.4 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 6.3 MB/s  0:00:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.0-cp312-cp312-win_amd64.whl (36.3 MB)
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   - -------------------------------------- 1.0/36.3 MB 7.2 MB/s eta 0:00:05
   -- ------------------------------------- 2.4/36.3 MB 6.1 MB/s eta 0:00:06
   ---- ----------------------------------- 3.9/36.3 MB 6.3 MB/s eta 0:00:06
   ------ --------------------------------- 5.5/36.3 MB 6.6 MB/s eta 0:00:05
   ------- -------------------------------- 6.8/36.3 MB 6.7 MB/s eta 0:00:05
   --------- ------------------------------ 8.4/36.3 MB 6.7 MB/s eta 0:00:05
   ---------- ----------------------------- 9.7/36.3 MB 6.7 MB/s eta 0:00:04
   ------------ --------------------------- 11.3/36.3 MB 6.7 MB/s eta 0:00:04
   -------------- ------------------------- 12.8/36.3 MB 6.8 MB/s eta 0:00:04
   --------------- ------------------------ 13.9/36.3 MB 6.7 MB/s eta 0:00:04
   ----------------- ---------------------- 15.5/36.3 MB 6.7 MB/s eta 0:00:04
   ------------------ --------------------- 17.0/36.3 MB 6.7 MB/s eta 0:00:03
   -------------------- ------------------- 18.4/36.3 MB 6.7 MB/s eta 0:00:03
   --------------------- ------------------ 19.9/36.3 MB 6.7 MB/s eta 0:00:03
   ----------------------- ---------------- 21.2/36.3 MB 6.7 MB/s eta 0:00:03
   ------------------------ --------------- 22.5/36.3 MB 6.7 MB/s eta 0:00:03
   -------------------------- ------------- 23.9/36.3 MB 6.7 MB/s eta 0:00:02
   --------------------------- ------------ 25.2/36.3 MB 6.7 MB/s eta 0:00:02
   ---------------------------- ----------- 25.7/36.3 MB 6.5 MB/s eta 0:00:02
   ------------------------------ --------- 27.3/36.3 MB 6.5 MB/s eta 0:00:02
   ------------------------------- -------- 28.6/36.3 MB 6.5 MB/s eta 0:00:02
   --------------------------------- ------ 30.1/36.3 MB 6.5 MB/s eta 0:00:01
   ---------------------------------- ----- 31.5/36.3 MB 6.5 MB/s eta 0:00:01
   ------------------------------------ --- 32.8/36.3 MB 6.5 MB/s eta 0:00:01
   ------------------------------------- -- 34.3/36.3 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  35.9/36.3 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 36.3/36.3 MB 6.4 MB/s  0:00:05
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.0 threadpoolctl-3.6.0