In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [6]:
df=pd.read_csv("C:\\Users\\rohit\\Downloads\\Travel.csv")

In [7]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [8]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [34]:
df["Gender"].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [12]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [15]:
df["TypeofContact"].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [31]:
df["Gender"]=df["Gender"].replace("Fe male","Female")

In [26]:
df["MaritalStatus"]=df["MaritalStatus"].replace("single","unmarried")

In [18]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [29]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [35]:
feature_with_na=[feature for feature in df.columns if df[feature].isnull().sum()>1]
for feature in feature_with_na:
    print(feature, np.round(df[feature].isnull().mean(),4), "% missing values")

Age 0.0462 % missing values
TypeofContact 0.0051 % missing values
DurationOfPitch 0.0514 % missing values
NumberOfFollowups 0.0092 % missing values
PreferredPropertyStar 0.0053 % missing values
NumberOfTrips 0.0286 % missing values
NumberOfChildrenVisiting 0.0135 % missing values
MonthlyIncome 0.0477 % missing values

In [36]:
df[feature_with_na].select_dtypes(exclude=["object"]).describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [39]:
df.Age.fillna(df.Age.median(), inplace=True)
df.TypeofContact.fillna(df.TypeofContact.mode()[0], inplace=True)
df.DurationOfPitch.fillna(df.DurationOfPitch.median(), inplace=True)
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.median(), inplace=True)
df.NumberOfPersonVisiting.fillna(df.NumberOfPersonVisiting.median(), inplace=True)
df.NumberOfFollowups.fillna(df.NumberOfFollowups.median(), inplace=True)
df.MaritalStatus.fillna(df.MaritalStatus.mode()[0], inplace=True)
df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.median(), inplace=True)

In [42]:
df["Totalvisiting"]=df["NumberOfPersonVisiting"]+df["NumberOfChildrenVisiting"]
df.drop(["NumberOfPersonVisiting","NumberOfChildrenVisiting"], axis=1, inplace=True)
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,Totalvisiting
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Single,1.0,1,2,1,Manager,20993.0,3.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Single,7.0,1,3,0,Executive,17090.0,3.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [43]:
num_features=[feature for feature in df.columns if df[feature].dtype!="O"]
print("Number of numerical features: ", len(num_features))
cat_features=[feature for feature in df.columns if df[feature].dtype=="O"]
print("Number of categorical features: ", len(cat_features))
discrete_features=[feature for feature in num_features if len(df[feature].unique())<25]
print("Number of discrete features: ", len(discrete_features))
continuous_features=[feature for feature in num_features if feature not in discrete_features]
print("Number of continuous features: ", len(continuous_features))

Number of numerical features:  13
Number of categorical features:  6
Number of discrete features:  9
Number of continuous features:  4

In [49]:
from sklearn.model_selection import train_test_split
X=df.drop("ProdTaken", axis=1)
y=df["ProdTaken"]
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=42)

In [47]:
cat_features=X.select_dtypes(include=["object"]).columns
num_features=X.select_dtypes(exclude=["object"]).columns
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop="first")
preprocessor=ColumnTransformer(
    [("oh", oh_transformer, cat_features),
     ("standardscaler", numeric_transformer, num_features)]
)

In [50]:
X_train=preprocessor.fit_transform(X_train)
X_test=preprocessor.transform(X_test)

In [53]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score, roc_auc_score
models={"Random Forest": RandomForestClassifier(),
        "Decision Tree": DecisionTreeClassifier()}
for i in range(len(models)):
    model=list(models.values())[i]
    model.fit(X_train, y_train)
    y_pred=model.predict(X_test)
    print(list(models.keys())[i])
    print("Classification Report: \n", classification_report(y_test, y_pred))
    print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
    print("Accuracy Score: ", accuracy_score(y_test, y_pred))
    print("F1 Score: ", f1_score(y_test, y_pred))
    print("ROC AUC Score: ", roc_auc_score(y_test, y_pred))

Random Forest
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.99      0.94       787
           1       0.94      0.55      0.69       191

    accuracy                           0.90       978
   macro avg       0.92      0.77      0.82       978
weighted avg       0.91      0.90      0.89       978

Confusion Matrix:
 [[780   7]
 [ 86 105]]
Accuracy Score:  0.9049079754601227
F1 Score:  0.693069306930693
ROC AUC Score:  0.7704218418409094
Decision Tree
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.94      0.93       787
           1       0.73      0.68      0.71       191

    accuracy                           0.89       978
   macro avg       0.83      0.81      0.82       978
weighted avg       0.89      0.89      0.89       978

Confusion Matrix:
 [[740  47]
 [ 61 130]]
Accuracy Score:  0.8895705521472392
F1 Score:  0.7065217391304348
ROC AUC Score:  0.810453907409009

In [54]:
y_train_pred=model.predict(X_train)
y_test_pred=model.predict(X_test)
print("Train Accuracy: ", accuracy_score(y_train, y_train_pred))
print("Test Accuracy: ", accuracy_score(y_test, y_test_pred))

Train Accuracy:  1.0
Test Accuracy:  0.8895705521472392

In [55]:
rf_params={"n_estimators": [100, 200, 300],
           "max_depth": [None, 10, 20],
              "min_samples_split": [2, 5, 10],
              "max_features": ["sqrt", "log2"]}

In [56]:
randomcv_models=[
    ("Rf", RandomForestClassifier(), rf_params)
]

In [57]:
from sklearn.model_selection import RandomizedSearchCV
model_param={}
for name, model, params in randomcv_models:
    randomcv=RandomizedSearchCV(model, params, cv=5, n_iter=10, scoring="accuracy", n_jobs=-1, verbose=2, random_state=42)
    randomcv.fit(X_train, y_train)
    model_param[name]=randomcv.best_params_

Fitting 5 folds for each of 10 candidates, totalling 50 fits

In [58]:
print(model_param)

{'Rf': {'n_estimators': 100, 'min_samples_split': 5, 'max_features': 'sqrt', 'max_depth': None}}